baseurl = "/"
languageCode = "en-us"
title = "The Miler Lab"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Us"
    url = "/about/"
[[menu.main]]
    name = "Publications"
    url = "https://www.ncbi.nlm.nih.gov/pubmed/?term=Miller%20DM%5BAuthor%5D&cauthor=true&cauthor_uid=29408204"
[[menu.main]]
    name = "MGH Cancer Center"
    url = "https://www.massgeneral.org/cancer-center"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

