---
title: "DMM Biography"
author: "David Miller"
date: "11/10/2019"
output: html_document
---

About David Miller, MD, PhD

**David M. Miller, MD, PhD** is a board-certified Dermatologist and Internist, as well as a board-eligible Hematologist and Medical Oncologist. 

Dr. Miller graduated with Honors from Boston College where he earned a BA in Political Science.  He received his medical (MD) and PhD degree in Biomedical Sciences from the University of Massachusetts.  While at UMass, Dr. Miller received the American Diabetes Association Physician-Scientist Training Award for three consecutive years, a Fuller Foundation grant, and he was inducted into the Alpha Omega Honor Society.  He then completed a Dermatology residency at Columbia University Medical Center, followed by a residency in Internal Medicine at Brigham and Women's Hospital.  Following both residencies, Dr. Miller completed fellowship training in Hematology/Oncology at Beth Israel Deaconess Medical Center.

Dr. Miller belongs to several professional organizations, including the American Academy of Dermatology, Medical Dermatology Society, and the American Society of Clinical Oncology.  He has numerous peer-reviewed publications and he has presented his work at the Society for Investigative Dermatology, New York Academy of Medicine, and the American Academy of Dermatology.  He is also a reviewer for the British Journal of Dermatology, Journal of Investigative Dermatology, JAEDV, and Clinical Cancer Research.

His research is focused on developing novel therapies for advanced skin cancer.  He has received support for his research from the NIH in the form of a loan repayment award, a grant from the American Skin Association and the Paul Carbone, MD fellowship award from ECOG-ACRIN. Dr. Miller's clinical interests include cutaneous oncology with a focus on the detection and treatment of high-risk skin cancers, Merkel cell carcinoma, melanoma, cutaneous lymphoma, general and complex medical dermatology.